### ISSUE TITLE
"Ich habe das nicht so gemeint"

### ISSUE THREAD

**Issue by paule96** [codez-one/CZ.Azure.FileExchange#18]
Wenn jemand ausversehen sein xxx-Video drag&drop auf den upload geschoben hat, sollte er die möglichkeit haben das aus der upload liste zu entfernen.

**Comment by kirkone** [comment]
Um es nochmal explizit zu beschreiben:

Die Einträge in der Liste der hochzuladenden Dateien sollten eine Möglichkeit bekommen nicht gewünschte Dateien wieder zu entfernen, bevor diese hochgeladen werden.

Ein Ansatz wäre zum Beispiel ein rotes "X" am rechten Rand des Elements.

Offene Fragen:

- [ ]  Soll das Entfernen nochmals bestätigt werden?
- [ ]  Soll ein entferntes Element verschwinden oder nur ausgegraut werden?

**Comment by kirkone** [comment]
closed with #19
